# Generated by Django 5.1.2 on 2024-10-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rudy_canary', '0003_githubtoken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
